name: flyingdarts_shared
description: Contains shared resources for application

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  widgetbook_annotation:
    path: ./../../dependencies/widgetbook/packages/widgetbook_annotation
    # git:
    #   url: https://github.com/mikepattyn/widgetbook.git
    #   path: packages/widgetbook_annotation  widgetbook_annotation:

  widgetbook:
    path: ./../../dependencies/widgetbook/packages/widgetbook
    # git:
    #   url: https://github.com/mikepattyn/widgetbook.git
    #   path: packages/widgetbook
  
dev_dependencies:
  build_runner:
  widgetbook_generator:
    path: ./../../dependencies/widgetbook/packages/widgetbook_generator
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true