name: dartboard
description: "A package containing the dartboard feature"
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_inappwebview: ^5.8.0
  
  ui:
    path: ./../../shared/ui

  internationalization:
    path: ./../../shared/internationalization

  widgetbook:
    path: ./../../../dependencies/widgetbook/packages/widgetbook

  widgetbook_annotation:
    path: ./../../../dependencies/widgetbook/packages/widgetbook_annotation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.4.6
  widgetbook_generator:
    path: ./../../../dependencies/widgetbook/packages/widgetbook_generator

flutter:
