name: flyingdarts

packages:
  - dependencies/*
  - packages/*

scripts:
  build_runner:
    run: melos exec --order-dependents -- dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner
  setup:
    run: melos bootstrap && melos run build_runner
  test:
    run: melos exec -- flutter test --concurrency=6
    packageFilters:
      dirExists: test
  clean_build_runner:
    run: melos exec -- dart run build_runner clean
    packageFilters:
      dependsOn: build_runner
  analyze-ci:
    run: melos exec -- flutter analyze --no-fatal-warnings --no-fatal-infos
  analyze:
    run: melos exec -- flutter analyze 
command:
  clean:
    hooks:
      post: melos run clean_build_runner
