name: flyingdarts_app
description: A flutter app to send score to Flyingdarts.net
publish_to: none

version: 1.3.9+1

environment:
  sdk: ">=2.18.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
    
  flyingdarts:
    path: ./packages/flyingdarts

  appbar:
    path: ./packages/features/appbar
  dartboard: 
    path: ./packages/features/dartboard
  keyboard:
    path: ./packages/features/keyboard
  language:
    path: ./packages/features/language
  navigation:
    path: ./packages/features/navigation
  profile:
    path: ./packages/features/profile
  speech:
    path: ./packages/features/speech

  internationalization:
    path: ./packages/shared/internationalization
  websocket:
    path: ./packages/shared/websocket
  ui: 
    path: ./packages/shared/ui

  flutter_bloc: ^8.1.3
  bloc: ^8.1.2

  provider: ^6.1.1
  
  widgetbook_annotation:
    path: ./dependencies/widgetbook/packages/widgetbook_annotation

  widgetbook:
    path: ./dependencies/widgetbook/packages/widgetbook

  amplify_auth_cognito: ^1.6.1
  amplify_authenticator: ^1.5.2
  amplify_flutter: ^1.6.0
  go_router: ^12.1.3
  loading_animation_widget: ^1.2.0+4
  flutter_svg: ^2.0.7
  curved_navigation_bar: ^1.0.3
  flutter_localizations:
    sdk: flutter
  melos: ^3.2.0
  get_it: ^7.6.4
  injectable: ^2.3.0
  speech_to_text: 
    git:
      url: https://github.com/flyingdarts/speech_to_text.git
      path: speech_to_text
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  rxdart: ^0.27.7
  bloc_test: ^9.1.5
  alchemist: ^0.7.0
  glob: ^2.1.2
  flutter_inappwebview: ^5.8.0
  intl: any
  equatable: ^2.0.5
  injectable_generator: ^2.3.0
  flutter_lints: ^3.0.1
  mockito: ^5.4.3
  build_runner: ^2.4.6
  test: ^1.24.3
  widgetbook_generator:
    path: ./dependencies/widgetbook/packages/widgetbook_generator
  gherkin: ^2.0.8
  flutter_gherkin: ^2.0.0

  dependency_validator: 

flutter:
  uses-material-design: true
  assets:
    - assets/icons/dartboard_icon.svg
    - assets/icons/dartboard_icon_outlined.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
