name: appbar
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  amplify_flutter: ^1.6.1

  ui: 
    path: ./../../shared/ui
    
  profile:
    path: ./../profile

  language:
    path: ./../language
  
  navigation:
    path: ./../navigation
    
  widgetbook:
    path: ./../../../dependencies/widgetbook/packages/widgetbook

  widgetbook_annotation:
    path: ./../../../dependencies/widgetbook/packages/widgetbook_annotation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.4.7
  widgetbook_generator:
    path: ./../../../dependencies/widgetbook/packages/widgetbook_generator

flutter:
