name: flyingdarts_features
description: Contains features for the application

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  bloc:
  speech_to_text:
    git:
      url: https://github.com/flyingdarts/speech_to_text.git
      path: speech_to_text
  equatable:
  flutter_inappwebview:
  
  flyingdarts_shared:
    path: ./../shared
  flyingdarts_internationalization:
    path: ./../internationalization
  widgetbook_annotation:
    path: ./../../dependencies/widgetbook/packages/widgetbook_annotation
  widgetbook:
    path: ./../../dependencies/widgetbook/packages/widgetbook
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  build_runner:
  widgetbook_generator:
    path: ./../../dependencies/widgetbook/packages/widgetbook_generator
flutter:
  uses-material-design: true
  assets:
    - assets/dartboard.html
  