name: navigation
description: "A package containing the navigation feature."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  amplify_flutter: ^1.6.1
  get_it: 
  dartboard: 
    path: ./../dartboard
    
  keyboard:
    path: ./../keyboard

  language:
    path: ./../language

  speech:
    path: ./../speech

  widgetbook:
    path: ./../../../dependencies/widgetbook/packages/widgetbook

  widgetbook_annotation:
    path: ./../../../dependencies/widgetbook/packages/widgetbook_annotation
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.4.6
  widgetbook_generator:
    path: ./../../../dependencies/widgetbook/packages/widgetbook_generator

flutter:
