// Mocks generated by Mockito 5.4.2 from annotations
// in iyltdsu_voice/presentation/bloc/camera/camera_bloc.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bloc/bloc.dart' as _i5;
import 'package:iyltdsu_voice/bloc/camera/camera_bloc.dart' as _i3;
import 'package:mobile_scanner/mobile_scanner.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMobileScannerController_0 extends _i1.SmartFake
    implements _i2.MobileScannerController {
  _FakeMobileScannerController_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCameraState_1 extends _i1.SmartFake implements _i3.CameraState {
  _FakeCameraState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CameraBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockCameraBloc extends _i1.Mock implements _i3.CameraBloc {
  @override
  _i2.MobileScannerController get controller => (super.noSuchMethod(
        Invocation.getter(#controller),
        returnValue: _FakeMobileScannerController_0(
          this,
          Invocation.getter(#controller),
        ),
        returnValueForMissingStub: _FakeMobileScannerController_0(
          this,
          Invocation.getter(#controller),
        ),
      ) as _i2.MobileScannerController);
  @override
  _i3.CameraState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeCameraState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeCameraState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.CameraState);
  @override
  _i4.Stream<_i3.CameraState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i3.CameraState>.empty(),
        returnValueForMissingStub: _i4.Stream<_i3.CameraState>.empty(),
      ) as _i4.Stream<_i3.CameraState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  void add(_i3.CameraEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onEvent(_i3.CameraEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void emit(_i3.CameraState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void on<E extends _i3.CameraEvent>(
    _i5.EventHandler<E, _i3.CameraState>? handler, {
    _i5.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onTransition(
          _i5.Transition<_i3.CameraEvent, _i3.CameraState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  void onChange(_i5.Change<_i3.CameraState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
