name: profile
description: "A package containg the profile feature."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3

  get_it: ^7.6.4

  amplify:
    path: ./../../shared/amplify

  ui:
    path: ./../../shared/ui

  websocket:
    path: ./../../shared/websocket

  widgetbook:
    path: ./../../../dependencies/widgetbook/packages/widgetbook

  widgetbook_annotation:
    path: ./../../../dependencies/widgetbook/packages/widgetbook_annotation
  json_annotation: ^4.8.0
  injectable: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.4.6
  widgetbook_generator:
    path: ./../../../dependencies/widgetbook/packages/widgetbook_generator
  json_serializable: ^6.7.1
  injectable_generator: ^2.3.0

flutter:
