name: flyingdarts
description: "A flutter package used to configure dependencies and modules"
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.6
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.0.15
  get_it: ^7.6.0
  injectable: ^2.3.0

  websocket:
    path: ./../shared/websocket
  configuration:
    path: ./../shared/configuration/core
  configuration_preferences:
    path: ./../shared/configuration/preferences
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  injectable_generator: ^2.3.0
  build_runner: ^2.4.6

flutter: